suman:
   server: <SUSE Manager server fqdn>
   user: <SUSE Manager account with enough rights to perform actions>
   password: <password>

smtp:
   # sendmail: True is a mail should be send for minor and major errors. False if no mail should be send     
   sendmail: True
   receivers:
     - <reciever 1>
     - <reciever 2>
   sender: <name of sender>
   server: <smtp server>

dirs:
   log_dir: <location of log file>


